import {
  metaMaskWallet,
  walletConnectWallet,
  trustWallet,
  okxWallet,
  binanceWallet,
  bitgetWallet,
  tokenPocketWallet,
  imTokenWallet,
  rabbyWallet,
  coinbaseWallet,
  rainbowWallet,
  phantomWallet,
  safepalWallet,
  bybitWallet,
  gateWallet,
  coin98Wallet,
  oneKeyWallet,
  ledgerWallet,
  braveWallet,
  zerionWallet,
  uniswapWallet,
  coreWallet,
  backpackWallet,
  safeWallet,
  injectedWallet,
  argentWallet,
  foxWallet,
  frontierWallet,
  enkryptWallet,
  tahoWallet,
  talismanWallet,
  subWallet,
  omniWallet,
  krakenWallet,
  geminiWallet,
  bestWallet,
} from '@rainbow-me/rainbowkit/wallets'

export const walletGroups = [
  {
    groupName: '热门钱包',
    wallets: [
      metaMaskWallet,
      trustWallet,
      okxWallet,
      binanceWallet,
      bitgetWallet,
      tokenPocketWallet,
      imTokenWallet,
      walletConnectWallet,
    ],
  },
  {
    groupName: '更多钱包',
    wallets: [
      rabbyWallet,
      coinbaseWallet,
      rainbowWallet,
      phantomWallet,
      safepalWallet,
      bybitWallet,
      gateWallet,
      coin98Wallet,
      oneKeyWallet,
      ledgerWallet,
      braveWallet,
      zerionWallet,
      uniswapWallet,
      coreWallet,
      backpackWallet,
      argentWallet,
      foxWallet,
      frontierWallet,
      enkryptWallet,
      tahoWallet,
      talismanWallet,
      subWallet,
      omniWallet,
      krakenWallet,
      geminiWallet,
      bestWallet,
    ],
  },
  {
    groupName: '其他',
    wallets: [safeWallet, injectedWallet],
  },
]
